### ISSUE TITLE
Server Error Log

### ISSUE THREAD

**Issue by NightSharp** [ModdingForBlockheads/Forbic#19]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.0.32

### Mod Version

3.0.2

### Describe the Issue

The server can start normally.
But there are some error reported in the server log

### Logs

[09:06:01] [ForkJoinPool.commonPool-worker-1/ERROR] [ne.mi.ev.EventSubclassTransformer/EVENTBUS]: Could not find parent net/blay09/mods/balm/api/event/BalmEvent for class net/blay09/mods/balm/api/event/server/ServerReloadedEvent in classloader jdk.internal.loader.ClassLoaders$AppClassLoader@e9e54c2 on thread Thread[ForkJoinPool.commonPool-worker-1,5,main] [09:06:01] [ForkJoinPool.commonPool-worker-1/ERROR] [ne.mi.ev.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler java.lang.ClassNotFoundException: net.blay09.mods.balm.api.event.BalmEvent         at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}         at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?] {}         at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}         at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar%232!/:?] {}         at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar%232!/:?] {}         at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar%232!/:?] {}         at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar%232!/:5.0.3+70+master.d7d405b] {}         at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?] {}         at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?] {}         at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?] {}         at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?] {}         at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}         at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}         at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}         at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}         at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}         at net.minecraft.server.ReloadableServerResources.md93fb14$lambda$loadResources$0$0(ReloadableServerResources.java:522) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:balm.mixins.json:ReloadableServerResourcesMixin,pl:mixin:A}         at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) [?:?] {}         at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?] {}         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}         at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}         at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {}         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {}

**Comment by BlayTheNinth** [comment]
This was most likely fixed by https://github.com/ModdingForBlockheads/Balm/commit/e6adc6262a761df52dc304954c9a80b70bde36d3 and should no longer happen on newer Balm versions.
