### ISSUE TITLE
IndexOutOfBoundsException in logs

### ISSUE THREAD

**Issue by spoorn** [ModdingForBlockheads/Forbic#20]
### Minecraft Version

1.18.x

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### Mod Version

3.0.0+0

### Describe the Issue

Saw these errors in the logs, I believe when I was using the Storage Network Remote from slotlink: https://www.curseforge.com/minecraft/mc-mods/slotlink

```
[16:41:29] [Render thread/ERROR]: Error executing task on Client
java.lang.IndexOutOfBoundsException: Index: 66, Size: 65
	at net.fabricmc.fabric.impl.client.screen.ButtonList.translateIndex(ButtonList.java:130) ~[fabric-screen-api-v1-1.0.10+d882b91560-6a4b3d97ee4954e2.jar:?]
	at net.fabricmc.fabric.impl.client.screen.ButtonList.add(ButtonList.java:82) ~[fabric-screen-api-v1-1.0.10+d882b91560-6a4b3d97ee4954e2.jar:?]
	at net.fabricmc.fabric.impl.client.screen.ButtonList.add(ButtonList.java:33) ~[fabric-screen-api-v1-1.0.10+d882b91560-6a4b3d97ee4954e2.jar:?]
	at java.util.AbstractList.add(AbstractList.java:111) ~[?:?]
	at net.blay09.mods.balm.fabric.client.screen.FabricBalmScreens.addRenderableWidget(FabricBalmScreens.java:23) ~[balm-fabric-3.0.0+0.jar:?]
	at net.blay09.mods.craftingtweaks.client.CraftingTweaksClient.lambda$screenInitialized$1(CraftingTweaksClient.java:272) ~[craftingtweaks-fabric-1.18-13.0.0.jar:?]
	at net.blay09.mods.craftingtweaks.api.impl.DefaultGridGuiHandler.createTweakButton(DefaultGridGuiHandler.java:36) ~[craftingtweaks-fabric-1.18-13.0.0.jar:?]
	at net.blay09.mods.craftingtweaks.api.impl.DefaultGridGuiHandler.createButtons(DefaultGridGuiHandler.java:24) ~[craftingtweaks-fabric-1.18-13.0.0.jar:?]
	at net.blay09.mods.craftingtweaks.client.CraftingTweaksClient.screenInitialized(CraftingTweaksClient.java:272) ~[craftingtweaks-fabric-1.18-13.0.0.jar:?]
	at net.blay09.mods.balm.fabric.event.FabricBalmEvents.fireEventHandler(FabricBalmEvents.java:41) ~[balm-fabric-3.0.0+0.jar:?]
	at net.blay09.mods.balm.fabric.event.FabricBalmEvents.lambda$fireEventHandlers$0(FabricBalmEvents.java:36) ~[balm-fabric-3.0.0+0.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.blay09.mods.balm.fabric.event.FabricBalmEvents.fireEventHandlers(FabricBalmEvents.java:36) ~[balm-fabric-3.0.0+0.jar:?]
	at net.blay09.mods.balm.fabric.event.client.FabricBalmClientEvents.lambda$registerEvents$13(FabricBalmClientEvents.java:105) ~[balm-fabric-3.0.0+0.jar:?]
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.lambda$static$2(ScreenEvents.java:103) ~[fabric-screen-api-v1-1.0.10+d882b91560-6a4b3d97ee4954e2.jar:?]
	at net.minecraft.class_437.handler$dcp000$afterInitScreen(class_437.java:5327) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:393) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:993) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.openScreen(ClientNetworking.java:86) ~[fabric-screen-handler-api-v1-1.1+40c91ec860-7ba2e3b6c38ee0b3.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.lambda$onInitializeClient$0(ClientNetworking.java:54) ~[fabric-screen-handler-api-v1-1.1+40c91ec860-7ba2e3b6c38ee0b3.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
```

**Comment by BlayTheNinth** [comment]
I don't think this is an issue in Balm / Crafting Tweaks as it's just calling a standard `add` on Fabric's buttons API. 
This is probably an issue in Fabric or the mod adding the screen being opened.
