### ISSUE TITLE
Updating from v4.2.0 to v4.3.0 causes error

### ISSUE THREAD

**Issue by ghost** [ModdingForBlockheads/Forbic#26]
### Minecraft Version

1.19.x

### Mod Loader

Fabric

### Mod Loader Version

0.14.8

### Mod Version

4.3.0

### Describe the Issue

Hello, I was updating the Balm version on my server and after a player tried to connect (via Geyser from Bedrock) it shows this error.

[19:11:04] [Server thread/ERROR]: Couldn't place player in world
java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /mnt/minecraft/mods/balm-fabric-4.2.0+0.jar
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at net.fabricmc.loader.impl.util.LoaderUtil.normalizeExistingPath(LoaderUtil.java:42) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getCodeSource(KnotClassDelegate.java:507) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getMetadata(KnotClassDelegate.java:355) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:330) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.blay09.mods.balm.api.network.SyncConfigMessage.writeSyncedFields(SyncConfigMessage.java:107) ~[balm-fabric-4.2.0+0.jar:?]
	at net.blay09.mods.balm.api.network.SyncConfigMessage.lambda$register$4(SyncConfigMessage.java:123) ~[balm-fabric-4.2.0+0.jar:?]
	at net.blay09.mods.balm.fabric.network.FabricBalmNetworking.sendTo(FabricBalmNetworking.java:92) ~[balm-fabric-4.2.0+0.jar:?]
	at net.blay09.mods.balm.api.config.AbstractBalmConfig.lambda$initialize$0(AbstractBalmConfig.java:25) ~[balm-fabric-4.2.0+0.jar:?]
	at net.blay09.mods.balm.fabric.event.FabricBalmEvents.fireEventHandler(FabricBalmEvents.java:41) ~[balm-fabric-4.2.0+0.jar:?]
	at net.blay09.mods.balm.fabric.event.FabricBalmEvents.lambda$fireEventHandlers$0(FabricBalmEvents.java:36) ~[balm-fabric-4.2.0+0.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.blay09.mods.balm.fabric.event.FabricBalmEvents.fireEventHandlers(FabricBalmEvents.java:36) ~[balm-fabric-4.2.0+0.jar:?]
	at net.blay09.mods.balm.fabric.event.FabricBalmCommonEvents.lambda$registerEvents$16(FabricBalmCommonEvents.java:91) ~[balm-fabric-4.2.0+0.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.0.27+7fe97409a9-48071ba5592ad07f.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:65) ~[fabric-networking-api-v1-1.0.27+7fe97409a9-48071ba5592ad07f.jar:?]
	at net.minecraft.server.PlayerManager.handler$dgi000$handlePlayerConnection(PlayerManager:7992) ~[?:?]
	at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager:197) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.addToServer(ServerLoginNetworkHandler:140) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler:127) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.redirect$dgj000$handlePlayerJoin(ServerLoginNetworkHandler:563) ~[?:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler:77) ~[?:?]
	at net.minecraft.network.ClientConnection.tick(ClientConnection:242) ~[?:?]
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:182) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:886) ~[server-intermediary.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:289) ~[?:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zgg000$modifiedRunLoop(MinecraftServer:4380) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:258) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.nio.file.NoSuchFileException: /mnt/minecraft/mods/balm-fabric-4.2.0+0.jar
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixPath.toRealPath(UnixPath.java:825) ~[?:?]
	at net.fabricmc.loader.impl.util.LoaderUtil.normalizeExistingPath(LoaderUtil.java:40) ~[fabric-loader-0.14.8.jar:?]
	... 32 more

I was downgrading to v4.2.0 and everything works now as usual (puh!).
Greetings.

**Comment by BlayTheNinth** [comment]
It's claiming to be unable to find `/mnt/minecraft/mods/balm-fabric-4.2.0+0.jar` and the logs claim to be running v4.2.0 rather than 4.3.0. This seems to be an issue with the server / client setup, not Balm.

**Comment by ghost** [comment]
I was looking again the log, yep, it was still loading the old .jar file (duh?!). 
Sorry for this.
