### ISSUE TITLE
Forge Crash

### ISSUE THREAD

**Issue by agabeluga** [ModdingForBlockheads/Forbic#27]
### Minecraft Version

1.19.x

### Mod Loader

Forge

### Mod Loader Version

1.19-41.0.63

### Mod Version

4.3.0

### Describe the Issue

The game opens for like 1 second. Then it crashed. 
On Forge Forums I was told this is the mod that crashes it.

### Logs

[07lip2022 18:29:06.635] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Alex2011mc, --version, 1.19-forge-41.0.63, --gameDir, C:\Users\amigo\AppData\Roaming\.minecraft, --assetsDir, C:\Users\amigo\AppData\Roaming\.minecraft\assets, --assetIndex, 1.19, --uuid, ecdf047c482c459b9bc57655ece4f05b, --accessToken, ????????, --clientId, YmQzNTQ4OWYtNGI1Zi00NzIxLWE0Y2UtOTMxODdlM2UyNzUz, --xuid, 2535420908239711, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 41.0.63, --fml.mcVersion, 1.19, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220607.102129]
[07lip2022 18:29:06.639] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.1+10.0.1+main.e9521dc3 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[07lip2022 18:29:06.835] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/amigo/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2390!/ Service=ModLauncher Env=CLIENT
[07lip2022 18:29:07.952] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\amigo\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.19-41.0.63\fmlcore-1.19-41.0.63.jar is missing mods.toml file
[07lip2022 18:29:07.955] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\amigo\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19-41.0.63\javafmllanguage-1.19-41.0.63.jar is missing mods.toml file
[07lip2022 18:29:07.958] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\amigo\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19-41.0.63\lowcodelanguage-1.19-41.0.63.jar is missing mods.toml file
[07lip2022 18:29:07.960] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\amigo\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.19-41.0.63\mclanguage-1.19-41.0.63.jar is missing mods.toml file
[07lip2022 18:29:08.059] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 1 dependencies adding them to mods collection
[07lip2022 18:29:10.716] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[07lip2022 18:29:10.993] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19-forge-41.0.63, --gameDir, C:\Users\amigo\AppData\Roaming\.minecraft, --assetsDir, C:\Users\amigo\AppData\Roaming\.minecraft\assets, --uuid, ecdf047c482c459b9bc57655ece4f05b, --username, Alex2011mc, --assetIndex, 1.19, --accessToken, ????????, --clientId, YmQzNTQ4OWYtNGI1Zi00NzIxLWE0Y2UtOTMxODdlM2UyNzUz, --xuid, 2535420908239711, --userType, msa, --versionType, release]
[07lip2022 18:29:11.152] [main/WARN] [mixin/]: Reference map 'morevillagers-forge-forge-refmap.json' for morevillagers.mixins.json could not be read. If this is a development environment you can ignore this message
[07lip2022 18:29:12.070] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/level/levelgen/structure/MineShaftPieces$MineShaftPiece (java.lang.ClassNotFoundException: net.minecraft.world.level.levelgen.structure.MineShaftPieces$MineShaftPiece)
[07lip2022 18:29:12.070] [main/WARN] [mixin/]: @Mixin target net.minecraft.world.level.levelgen.structure.MineShaftPieces$MineShaftPiece was not found supplementaries.mixins.json:accessors.MineshaftAccessor
[07lip2022 18:29:12.229] [main/WARN] [mixin/]: Error loading class: de/maxhenkel/gravestone/events/DeathEvents (java.lang.ClassNotFoundException: de.maxhenkel.gravestone.events.DeathEvents)
[07lip2022 18:29:12.234] [main/WARN] [mixin/]: Error loading class: de/maxhenkel/corpse/events/DeathEvents (java.lang.ClassNotFoundException: de.maxhenkel.corpse.events.DeathEvents)
[07lip2022 18:29:12.431] [main/WARN] [mixin/]: Error loading class: me/cominixo/betterf3/modules/TargetModule (java.lang.ClassNotFoundException: me.cominixo.betterf3.modules.TargetModule)
[07lip2022 18:29:12.431] [main/WARN] [mixin/]: @Mixin target me.cominixo.betterf3.modules.TargetModule was not found securitycraft.mixins.json:f3.BetterF3TargetModuleMixin
[07lip2022 18:29:12.734] [main/INFO] [mixin/]: Mixing TextColorMixin from iceberg.mixins.json into net.minecraft.network.chat.TextColor
[07lip2022 18:29:13.374] [main/INFO] [mixin/]: Mixing MinecraftMixin from iceberg.mixins.json into net.minecraft.client.Minecraft
[07lip2022 18:29:13.405] [main/WARN] [mixin/]: @Redirect conflict. Skipping securitycraft.mixins.json:camera.MinecraftMixin->@Redirect::handleKeybinds(Lnet/minecraft/client/Options;Lnet/minecraft/client/CameraType;)V with priority 1100, already redirected by ars_nouveau.mixins.json:camera.MinecraftMixin->@Redirect::handleKeybinds(Lnet/minecraft/client/Options;Lnet/minecraft/client/CameraType;)V with priority 1100
[07lip2022 18:29:13.473] [main/INFO] [mixin/]: Mixing ScreenMixin from iceberg.mixins.json into net.minecraft.client.gui.screens.Screen
[07lip2022 18:29:13.729] [main/WARN] [mixin/]: @Inject(@At("HEAD")) Shift.BY=1 on blueprint.mixins.json:EntityMixin::handler$zpa000$baseTick exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[07lip2022 18:29:15.524] [pool-3-thread-1/INFO] [net.minecraft.util.datafix.DataFixers/]: Building optimized datafixer
[07lip2022 18:29:16.133] [pool-3-thread-1/WARN] [mixin/]: @Redirect conflict. Skipping ars_nouveau.mixins.json:camera.ANServerPlayerMixin->@Redirect::an_tick(Lnet/minecraft/server/level/ServerPlayer;DDDFF)V with priority 1000, already redirected by securitycraft.mixins.json:camera.ServerPlayerMixin->@Redirect::tick(Lnet/minecraft/server/level/ServerPlayer;DDDFF)V with priority 1100
[07lip2022 18:29:18.839] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResources/]: Assets URL 'union:/C:/Users/amigo/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.19-20220607.102129/client-1.19-20220607.102129-srg.jar%23324!/assets/.mcassetsroot' uses unexpected schema
[07lip2022 18:29:18.839] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResources/]: Assets URL 'union:/C:/Users/amigo/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.19-20220607.102129/client-1.19-20220607.102129-srg.jar%23324!/data/.mcassetsroot' uses unexpected schema
[07lip2022 18:29:18.858] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[07lip2022 18:29:19.398] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: Alex2011mc
[07lip2022 18:29:19.608] [Render thread/INFO] [defaultoptions/]: Loaded default options for extra-folder
[07lip2022 18:29:19.674] [Render thread/ERROR] [net.minecraft.client.Options/]: Error parsing option value 0 for option Max Framerate: Value 0 outside of range [10:260]
[07lip2022 18:29:19.706] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.3.1 build 7
[07lip2022 18:29:19.820] [Render thread/INFO] [KubeJS/]: Loaded client.properties
[07lip2022 18:29:21.488] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: File C:\Users\amigo\AppData\Roaming\.minecraft\mods\connectivity-fabric-1.19-3.2.jar constructed 0 mods: [], but had 1 mods specified: [connectivity]
[07lip2022 18:29:21.622] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Failed to initialize mod containers
net.minecraftforge.fml.ModLoadingException: The Mod File C:\Users\amigo\AppData\Roaming\.minecraft\mods\connectivity-fabric-1.19-3.2.jar has mods that were not found
	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:263) ~[fmlcore-1.19-41.0.63.jar%23325!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:175) ~[fmlcore-1.19-41.0.63.jar%23325!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:92) ~[forge-1.19-41.0.63-universal.jar%23329!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:112) ~[forge-1.19-41.0.63-universal.jar%23329!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:92) ~[forge-1.19-41.0.63-universal.jar%23329!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:454) ~[client-1.19-20220607.102129-srg.jar%23324!/:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.19-20220607.102129-srg.jar%23324!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.63.jar%2393!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.1.jar:?]
[07lip2022 18:29:21.681] [Render thread/WARN] [net.minecraft.server.packs.repository.Pack/]: Couldn't get pack info for: net.minecraft.server.packs.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack 'C:\Users\amigo\AppData\Roaming\.minecraft\resourcepacks\Faithful-Java-64x-1.19.zip'
[07lip2022 18:29:21.695] [Render thread/WARN] [net.minecraft.server.packs.repository.Pack/]: Couldn't get pack info for: net.minecraft.server.packs.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack 'C:\Users\amigo\AppData\Roaming\.minecraft\resourcepacks\Java-32x-1.19.zip'
[07lip2022 18:29:21.854] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
[07lip2022 18:29:22.026] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Block to a broken mod state
[07lip2022 18:29:22.029] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Item to a broken mod state
[07lip2022 18:29:22.407] [Render thread/WARN] [mixin/]: @Redirect conflict. Skipping securitycraft.mixins.json:camera.LevelRendererMixin->@Redirect::onRepositionCamera(Lnet/minecraft/client/renderer/ViewArea;DD)V with priority 1100, already redirected by ars_nouveau.mixins.json:camera.LevelRendererMixin->@Redirect::onRepositionCamera(Lnet/minecraft/client/renderer/ViewArea;DD)V with priority 1100
[07lip2022 18:29:22.682] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ParticleFactoryRegisterEvent to a broken mod state
[07lip2022 18:29:22.803] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[07lip2022 18:29:22.876] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientReloadListenersEvent to a broken mod state
[07lip2022 18:29:22.876] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state
[07lip2022 18:29:22.876] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state
[07lip2022 18:29:23.034] [Render thread/INFO] [net.minecraft.server.packs.resources.ReloadableResourceManager/]: Reloading ResourceManager: Default, Jicklus+1.19.zip
[07lip2022 18:29:23.242] [Worker-Main-15/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelRegistryEvent to a broken mod state
[07lip2022 18:29:23.248] [Render thread/ERROR] [net.minecraft.client.main.Main/]: Unhandled game exception
java.lang.ExceptionInInitializerError: null
	at net.minecraft.client.Minecraft.handler$zef000$run(Minecraft.java:4255) ~[client-1.19-20220607.102129-srg.jar%23324!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java) ~[client-1.19-20220607.102129-srg.jar%23324!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%23324!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.63.jar%2393!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.1.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.getModEventBus()" because the return value of "net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.get()" is null
	at net.blay09.mods.balm.forge.world.ForgeBalmWorldGen.<init>(ForgeBalmWorldGen.java:63) ~[balm-4.3.0.jar%23159!/:4.3.0]
	at net.blay09.mods.balm.forge.ForgeBalmRuntime.<init>(ForgeBalmRuntime.java:53) ~[balm-4.3.0.jar%23159!/:4.3.0]
	at net.blay09.mods.balm.forge.ForgeBalmRuntimeFactory.create(ForgeBalmRuntimeFactory.java:9) ~[balm-4.3.0.jar%23159!/:4.3.0]
	at net.blay09.mods.balm.api.BalmRuntimeSpi.create(BalmRuntimeSpi.java:9) ~[balm-4.3.0.jar%23159!/:4.3.0]
	at net.blay09.mods.balm.api.Balm.<clinit>(Balm.java:25) ~[balm-4.3.0.jar%23159!/:4.3.0]
	... 16 more
[07lip2022 18:29:23.250] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!
[07lip2022 18:29:23.404] [Worker-Main-12/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[07lip2022 18:29:23.404] [Worker-Main-21/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[07lip2022 18:29:23.487] [Worker-Main-16/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[07lip2022 18:29:23.700] [Render thread/ERROR] [net.minecraft.client.Minecraft/]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.client.renderer.texture.TextureManager.close(TextureManager.java:176) ~[client-1.19-20220607.102129-srg.jar%23324!/:?]
	at net.minecraft.client.Minecraft.close(Minecraft.java:992) ~[client-1.19-20220607.102129-srg.jar%23324!/:?]
	at net.minecraft.client.Minecraft.m_91393_(Minecraft.java:966) ~[client-1.19-20220607.102129-srg.jar%23324!/:?]
	at net.minecraft.client.main.Main.main(Main.java:221) ~[client-1.19-20220607.102129-srg.jar%23324!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.63.jar%2393!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%2381!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.1.jar:?]

**Comment by BlayTheNinth** [comment]
Those logs are 99% OptiFine, are you sure that's the correct log?

**Comment by agabeluga** [comment]
I changed it.

**Comment by BlayTheNinth** [comment]
The Forge forum lied to you, the actual cause is something related to the mod "connectivity".

> [07lip2022 18:29:21.622] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Failed to initialize mod containers
net.minecraftforge.fml.ModLoadingException: The Mod File C:\Users\amigo\AppData\Roaming.minecraft\mods\connectivity-fabric-1.19-3.2.jar has mods that were not found

**Comment by agabeluga** [comment]
It was fabric
