### ISSUE TITLE
Blam biome incompatibility with Amplified Nether

### ISSUE THREAD

**Issue by jeseibel** [ModdingForBlockheads/Forbic#34]
### Minecraft Version

1.19.x

### Mod Loader

Forge

### Mod Loader Version

42.0.0

### Mod Version

4.5.3

### Describe the Issue

There appears to be an inconsistent incompatibility between Blam and [Amplified_Nether_v1.2](https://www.curseforge.com/minecraft/mc-mods/amplified-nether/).

Specifically relating to a biome that Blam adds:
```
[Render thread/WARN] [net.minecraft.client.gui.screens.worldselection.WorldOpenFlows/]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: com.google.gson.JsonParseException: Error loading registry data: Unknown registry key in ResourceKey[minecraft:root / forge:biome_modifier_serializers]: balm:balm

...

Caused by: com.google.gson.JsonParseException: Error loading registry data: Unknown registry key in ResourceKey[minecraft:root / forge:biome_modifier_serializers]: balm:balm
```

The issue only comes up every 5th launch or so and rebooting MC seems to fix the issue; so, it may have something to do with the order forge is loading mods.

**Full logs:**
[2022-08-15-9.log.gz](https://github.com/ModdingForBlockheads/Balm/files/9343965/2022-08-15-9.log.gz)
[2022-08-15-12.log.gz](https://github.com/ModdingForBlockheads/Balm/files/9343966/2022-08-15-12.log.gz)
[2022-08-15-16.log.gz](https://github.com/ModdingForBlockheads/Balm/files/9343967/2022-08-15-16.log.gz)

**Mod List:**
- AmbientSounds_FORGE_v5.2.1_mc1.19
- Amplified_Nether_v1.2
- balm-4.5.3
- CraftPresence-Forge-1.19.1-Release-1.8.9
- CreativeCore_FORGE_v2.7.4_mc1.19
- DistantHorizons-1.6.8a-1.19.1
- preview_OptiFine_1.19.1_HD_U_H9_pre1
- soundphysics-forge-1.19-1.0.9
- twilightforest-1.19-4.2.1381-universal
- waystones-forge-1.19-11.1.0

**Comment by BlayTheNinth** [comment]
There is an odd error happening before that is likely the cause:

```
[15Aug2022 19:06:46.004] [modloading-worker-0/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Error registering event handler: class net.minecraftforge.registries.RegisterEvent public void net.minecraftforge.registries.DeferredRegister$EventDispatcher.handleEvent(net.minecraftforge.registries.RegisterEvent)
java.lang.ClassNotFoundException: net.minecraftforge.registries.__EventDispatcher_handleEvent_RegisterEvent
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.<init>(ASMEventHandler.java:50) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:254) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:150) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$registerObject$6(EventBus.java:98) ~[eventbus-6.0.0.jar%2378!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.lambda$registerObject$7(EventBus.java:98) ~[eventbus-6.0.0.jar%2378!/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:94) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-6.0.0.jar%2378!/:?]
	at net.minecraftforge.registries.DeferredRegister.register(DeferredRegister.java:316) ~[forge-1.19.1-42.0.0-universal.jar%23158!/:?]
	at net.blay09.mods.balm.forge.world.ForgeBalmWorldGen.<init>(ForgeBalmWorldGen.java:65) ~[balm-4.5.3.jar%23146!/:4.5.3]
	at net.blay09.mods.balm.forge.ForgeBalmRuntime.<init>(ForgeBalmRuntime.java:53) ~[balm-4.5.3.jar%23146!/:4.5.3]
	at net.blay09.mods.balm.forge.ForgeBalmRuntimeFactory.create(ForgeBalmRuntimeFactory.java:9) ~[balm-4.5.3.jar%23146!/:4.5.3]
	at net.blay09.mods.balm.api.BalmRuntimeSpi.create(BalmRuntimeSpi.java:9) ~[balm-4.5.3.jar%23146!/:4.5.3]
	at net.blay09.mods.balm.api.Balm.<clinit>(Balm.java:25) ~[balm-4.5.3.jar%23146!/:4.5.3]
	at net.blay09.mods.waystones.ForgeWaystones.<init>(ForgeWaystones.java:14) ~[waystones-forge-1.19-11.1.0.jar%23152!/:11.1.0]
```

I'd suggest updating Forge and all mods in the pack or updating to 1.19.2 or higher, as this isn't a traditional error and something appears to be very broken in that instance.
