### ISSUE TITLE
1.18.2 Rendering Crash after updating from 3.2.5 to 3.2.6

### ISSUE THREAD

**Issue by border999** [ModdingForBlockheads/Forbic#51]
### Minecraft Version

1.18.2

### Mod Loader

Forge

### Mod Loader Version

40.2.0

### Mod Version

3.2.6

### Balm Version

3.2.6

### Describe the Issue

Rendering crash when starting up minecraft after updating Balm.
https://gist.github.com/border999/4bd704fa8c36a40afbad92667390ea02

**Comment by border999** [comment]
seems like the crash did not reoccur when I loaded minecraft again, some kind of growing pain crash?

**Comment by BlayTheNinth** [comment]
This does not seem to be related to Balm, but EnderStorage / CodeChickenLib:

```
Caused by: java.lang.ClassCastException: class [Lcodechicken.lib.vec.Vector3; cannot be cast to class codechicken.lib.render.model.ModelMaterial ([Lcodechicken.lib.vec.Vector3; and codechicken.lib.render.model.ModelMaterial are in module codechickenlib@4.1.3.480 of loader 'TRANSFORMER' @47bfde21)
	at codechicken.lib.render.model.ModelMaterial$1.copyRange(ModelMaterial.java:14) ~[CodeChickenLib-1.18.2-4.1.3.480-universal.jar%23196!/:4.1.3.480] {re:classloading}
	at codechicken.lib.render.CCModel.copy(CCModel.java:583) ~[CodeChickenLib-1.18.2-4.1.3.480-universal.jar%23196!/:4.1.3.480] {re:classloading}
	at codechicken.lib.render.CCModel.copy(CCModel.java:786) ~[CodeChickenLib-1.18.2-4.1.3.480-universal.jar%23196!/:4.1.3.480] {re:classloading}
	at codechicken.enderstorage.client.render.tile.RenderTileEnderTank.<clinit>(RenderTileEnderTank.java:48) ~[EnderStorage-1.18.2-2.9.0.182-universal.jar%23306!/:1.18.2-2.9.0.182] {re:classloading}
```

**Comment by border999** [comment]
https://github.com/TheCBProject/CodeChickenLib/issues/434

**Comment by border999** [comment]
[hs_err_pid16092.log](https://github.com/TwelveIterationMods/Balm/files/11012305/hs_err_pid16092.log)
also appears I am unable to enter the end now as well.
