### ISSUE TITLE
Update to 1.20.6

### ISSUE THREAD

**Issue by sternschnaube** [ModdingForBlockheads/Forbic#79]
### Minecraft Version

Other (specify below)

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Mod Version

Latest

### Balm Version

Latest

### Describe the Issue

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'balm-fabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:484)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.blay09.mods.balm.api.Balm
		at net.blay09.mods.balm.fabric.client.FabricBalmClientRuntime.createKeyMappingsBindings(FabricBalmClientRuntime.java:74)
		at net.blay09.mods.balm.fabric.client.FabricBalmClientRuntime.<init>(FabricBalmClientRuntime.java:31)
		at net.blay09.mods.balm.fabric.client.FabricBalmClientRuntimeFactory.create(FabricBalmClientRuntimeFactory.java:9)
		at net.blay09.mods.balm.api.client.BalmClientRuntimeSpi.create(BalmClientRuntimeSpi.java:9)
		at net.blay09.mods.balm.api.client.BalmClient.<clinit>(BalmClient.java:13)
		at net.minecraft.class_304.modify$zhk000$balm-fabric$ctor(class_304.java:1524)
		at net.minecraft.class_304.<init>(class_304.java:100)
		at marsh.town.brb.BetterRecipeBook.<clinit>(BetterRecipeBook.java:32)
		at marsh.town.brb.fabric.BetterRecipeBookFabric.onInitialize(BetterRecipeBookFabric.java:9)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
		... 6 more
	Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/item/v1/FabricItemSettings [in thread "Render thread"]
		at net.blay09.mods.balm.fabric.FabricBalmRuntime.<init>(FabricBalmRuntime.java:61)
		at net.blay09.mods.balm.fabric.FabricBalmRuntimeFactory.create(FabricBalmRuntimeFactory.java:9)
		at net.blay09.mods.balm.api.BalmRuntimeSpi.create(BalmRuntimeSpi.java:9)
		at net.blay09.mods.balm.api.Balm.<clinit>(Balm.java:27)
		at net.blay09.mods.balm.fabric.FabricBalm.onInitialize(FabricBalm.java:26)
		... 7 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.blay09.mods.balm.api.client.BalmClient
		at net.minecraft.class_304.modify$zhk000$balm-fabric$ctor(class_304.java:1524)
		at net.minecraft.class_304.<init>(class_304.java:100)
		at rogo.renderingculling.api.ModLoader.<clinit>(ModLoader.java:108)
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Class.java:534)
		at java.base/java.lang.Class.forName(Class.java:513)
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
		... 6 more
	Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: Could not initialize class net.blay09.mods.balm.api.Balm [in thread "Render thread"]
		at net.blay09.mods.balm.fabric.client.FabricBalmClientRuntime.createKeyMappingsBindings(FabricBalmClientRuntime.java:74)
		at net.blay09.mods.balm.fabric.client.FabricBalmClientRuntime.<init>(FabricBalmClientRuntime.java:31)
		at net.blay09.mods.balm.fabric.client.FabricBalmClientRuntimeFactory.create(FabricBalmClientRuntimeFactory.java:9)
		at net.blay09.mods.balm.api.client.BalmClientRuntimeSpi.create(BalmClientRuntimeSpi.java:9)
		at net.blay09.mods.balm.api.client.BalmClient.<clinit>(BalmClient.java:13)
		at net.minecraft.class_304.modify$zhk000$balm-fabric$ctor(class_304.java:1524)
		at net.minecraft.class_304.<init>(class_304.java:100)
		at marsh.town.brb.BetterRecipeBook.<clinit>(BetterRecipeBook.java:32)
		at marsh.town.brb.fabric.BetterRecipeBookFabric.onInitialize(BetterRecipeBookFabric.java:9)
		... 7 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.blay09.mods.balm.api.Balm
		at net.blay09.mods.kleeslabs.fabric.FabricKleeSlabs.onInitialize(FabricKleeSlabs.java:10)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
		... 6 more
	Caused by: [CIRCULAR REFERENCE: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/item/v1/FabricItemSettings [in thread "Render thread"]]
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.blay09.mods.balm.api.client.BalmClient
		at net.minecraft.class_304.modify$zhk000$balm-fabric$ctor(class_304.java:1524)
		at net.minecraft.class_304.<init>(class_304.java:100)
		at net.minecraft.class_304.<init>(class_304.java:90)
		at naqaden.namepain.NamePain.onInitialize(NamePain.java:38)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
		... 6 more
	Caused by: [CIRCULAR REFERENCE: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: Could not initialize class net.blay09.mods.balm.api.Balm [in thread "Render thread"]]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/item/v1/FabricItemSettings
	at net.blay09.mods.balm.fabric.FabricBalmRuntime.<init>(FabricBalmRuntime.java:61)
	at net.blay09.mods.balm.fabric.FabricBalmRuntimeFactory.create(FabricBalmRuntimeFactory.java:9)
	at net.blay09.mods.balm.api.BalmRuntimeSpi.create(BalmRuntimeSpi.java:9)
	at net.blay09.mods.balm.api.Balm.<clinit>(Balm.java:27)
	at net.blay09.mods.balm.fabric.FabricBalm.onInitialize(FabricBalm.java:26)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.item.v1.FabricItemSettings
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 12 more

**Comment by BlayTheNinth** [comment]
Please don't create issues for new Minecraft versions. I am aware of new releases and will port my mods when I have time and deem it appropriate (i.e. things appear stable enough).

If you'd like to be notified about releases, you can instead follow the projects on CurseForge or Modrinth, or join our [Discord](https://discord.gg/VAfZ2Nau6j).

**Comment by sternschnaube** [comment]
Thanks 😊
