### ISSUE TITLE
Mod doesn't work server-side

### ISSUE THREAD

**Issue by sternschnaube** [ModdingForBlockheads/Forbic#81]
### Minecraft Version

1.20.6

### Mod Loader

Fabric

### Mod Loader Version

0.15.11

### Mod Version

Latest

### Balm Version

Latest

### Describe the Issue

Received unknown remote registry entries from server
FabricRegistrySync
Render thread
Registry entry (team_reborn_energy:energy) is missing from local registry (minecraft:data_component_type)
net.fabricmc.fabric.impl.client.registry.sync.FabricRegistryClientInit
Render thread
Registry remapping failed!
java.util.concurrent.CompletionException: net.fabricmc.fabric.impl.registry.sync.RemapException: Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

team_reborn_energy

	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:145)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.mixinextras$bridge$method_18859$5(class_4093.java)
	at net.minecraft.class_4093.wrapOperation$den000$carpet-tis-addition$yeetUpdateSuppressionCrash_implForThreadExecutorTaskExecuting(class_4093.java:570)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.fabric.impl.registry.sync.RemapException: Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

team_reborn_energy

	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.checkRemoteRemap(RegistrySyncManager.java:364)
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:260)
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:142)
	... 13 more
net.minecraft.class_8673
Render thread
Client disconnected with reason: Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

team_reborn_energy

**Comment by BlayTheNinth** [comment]
Please provide the full logs. You can find the logs in the `logs` directory of the client or server. Most of the time `latest.log` is the correct file (unless the crash or issue happened during an earlier run).

Logs can be uploaded here by dragging the file into the comment field, or you can post them on a site like https://gist.github.com/ or https://pastebin.com/. Make sure they are set to be `public` (or unlisted) and to `never expire`.

**Comment by sternschnaube** [comment]
https://pastebin.com/raw/9hCBK1xz

**Comment by BlayTheNinth** [comment]
Does [this build](https://maven.twelveiterations.com/repository/maven-public/net/blay09/mods/balm-fabric/10.1.0-SNAPSHOT/balm-fabric-10.1.0-20240524.143333-21.jar) fix the issue?

**Comment by sternschnaube** [comment]
Still present. 

https://pastebin.com/raw/j7hddb6i

**Comment by BlayTheNinth** [comment]
Right, I think I understand now that you're using Balm either only on the client or only on the server (that kind of information is best provided in `Describe the Issue` because it will save both of us time).

The new Balm 10.0.2 decouples Reborn Energy API instead of shipping it so that it can once again be used on client-only/server-only.

**Comment by sternschnaube** [comment]
Thanks for the fix! 😄
