### ISSUE TITLE
Failed loading config file balm-common.toml of type COMMON for modid balm (Rendering overlay)

### ISSUE THREAD

**Issue by BlottaOver** [ModdingForBlockheads/Forbic#91]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

47.3.5

### Mod Version

all of the versions 

### Balm Version

the new one

### Describe the Issue

basically, I try to enter the game, load it, but when it opens, it just crashes

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-08-08 19:15:39
Description: Rendering overlay

net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file balm-common.toml of type COMMON for modid balm
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:47) ~[fmlcore-1.20.1-47.3.5.jar#213!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:60) ~[fmlcore-1.20.1-47.3.5.jar#213!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.20.1-47.3.5.jar#213!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:computing_frames,re:mixin}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.20.1-47.3.5.jar#213!/:?] {}
	at net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:68) ~[forge-1.20.1-47.3.5-universal.jar#217!/:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.handleInlineTransition(ModLoader.java:217) ~[fmlcore-1.20.1-47.3.5.jar#213!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:209) ~[fmlcore-1.20.1-47.3.5.jar#213!/:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:209) ~[fmlcore-1.20.1-47.3.5.jar#213!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$loadMods$15(ModLoader.java:190) ~[fmlcore-1.20.1-47.3.5.jar#213!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:computing_frames,re:mixin}
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:190) ~[fmlcore-1.20.1-47.3.5.jar#213!/:?] {}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$startModLoading$5(ClientModLoader.java:97) ~[forge-1.20.1-47.3.5-universal.jar#217!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:89) ~[forge-1.20.1-47.3.5-universal.jar#217!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.startModLoading(ClientModLoader.java:97) ~[forge-1.20.1-47.3.5-universal.jar#217!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$onResourceReload$2(ClientModLoader.java:80) ~[forge-1.20.1-47.3.5-universal.jar#217!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:89) ~[forge-1.20.1-47.3.5-universal.jar#217!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) ~[core-3.6.4.jar#93!/:?] {}
	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36) ~[core-3.6.4.jar#93!/:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49) ~[core-3.6.4.jar#93!/:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123) ~[core-3.6.4.jar#93!/:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166) ~[toml-3.6.4.jar#94!/:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145) ~[toml-3.6.4.jar#94!/:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.4.jar#94!/:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.4.jar#94!/:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.4.jar#94!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.4.jar#93!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.4.jar#93!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.4.jar#93!/:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.4.jar#93!/:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.4.jar#93!/:?] {}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:43) ~[fmlcore-1.20.1-47.3.5.jar#213!/:?] {}
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:47) ~[fmlcore-1.20.1-47.3.5.jar#213!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:60) ~[fmlcore-1.20.1-47.3.5.jar#213!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.20.1-47.3.5.jar#213!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:computing_frames,re:mixin}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.20.1-47.3.5.jar#213!/:?] {}
	at net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:68) ~[forge-1.20.1-47.3.5-universal.jar#217!/:?] {re:classloading}
-- Overlay render details --
Details:
	Overlay name: net.minecraftforge.client.loading.ForgeLoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:957) ~[client-1.20.1-20230612.114412-srg.jar#212!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar#212!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar#212!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.3.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.5.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.5.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, mod_resources

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 239422592 bytes (228 MiB) / 671088640 bytes (640 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2507
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6070
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 24959.92
	Virtual memory used (MB): 11657.31
	Swap memory total (MB): 8704.00
	Swap memory used (MB): 127.95
	JVM Flags: 8 total; -XX: UnlockExperimentalVMOptions -XX: UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: 1.20.1-forge-47.3.5
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 3050/PCIe/SSE2 GL version 4.6.0 NVIDIA 560.70, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: 
	Current Language: pt_br
	CPU: 12x Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	ModLauncher: 10.0.9 10.0.9 main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: ****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****
		lucky-block-forge-1.20.1-13.0.jar                 |Lucky Block                   |lucky                         |1.20.1-13.0         |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.20-3.0.0.163.jar             |TerraBlender                  |terrablender                  |**.**.**.**           |COMMON_SET|Manifest: NOSIGNATURE
		RegionsUnexploredForge-0.5.3 1.20.1.jar           |Regions Unexplored            |regions_unexplored            |0.5.3               |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.33_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.11.33             |COMMON_SET|Manifest: NOSIGNATURE
		simply_swords_with_epicfight_mod_1.20.1.jar       |simply swords with epicfight  |simply_swords_with_epicfight  |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.1.0.19.jar                    |Just Enough Items             |jei                           |**.**.**.**           |COMMON_SET|Manifest: NOSIGNATURE
		libraryferret-forge-1.20.1-4.0.0.jar              |Library ferret                |libraryferret                 |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedcore-1.20.1-0.5.71.324.jar           |Sophisticated Core            |sophisticatedcore             |1.20.1-0.5.71.324   |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.20-14.0.0.jar                   |Waystones                     |waystones                     |14.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		EpicFight-20.7.4.jar                              |Epic Fight                    |epicfight                     |20.7.4              |COMMON_SET|Manifest: NOSIGNATURE
		WeaponsOfMiracles-20.1.7.39.jar                   |Weapons of Minecraft          |wom                           |**.**.**.**           |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.20.1-5.9.9-forge.jar                 |Journeymap                    |journeymap                    |5.9.9               |COMMON_SET|Manifest: NOSIGNATURE
		awesomedungeon-forge-1.20.1-3.2.0.jar             |Awesome dungeon               |awesomedungeon                |3.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		TravelersBackpack-1.20.1-9.1.2.jar                |Traveler's Backpack           |travelersbackpack             |9.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		soul_like_armors_reworked_1.20.1_v54.0.jar        |soul like armors reworked     |soul_like_armors_reworked     |54.0                |COMMON_SET|Manifest: NOSIGNATURE
		invhud.forge.1.20-3.4.13.jar                      |Inventory HUD (Forge edition) |inventoryhud                  |3.4.13              |COMMON_SET|Manifest: NOSIGNATURE
		epic_simply_swords_mod_1.20.1_(v19).jar           |epic simply swords            |epic_simply_swords            |19                  |COMMON_SET|Manifest: NOSIGNATURE
		Dungeon Crawl-1.20.1-2.3.14.jar                   |Dungeon Crawl                 |dungeoncrawl                  |2.3.14              |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.20.1-3.18.51.855.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.20.1-3.18.51.855  |COMMON_SET|Manifest: NOSIGNATURE
		MoreVanillaArmor-Mod-Forge-1.20.1.jar             |MoreVanillaArmor              |morevanillaarmor              |1.20.1-5.1.0        |COMMON_SET|Manifest: NOSIGNATURE
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.1.4.jar                       |Balm                          |balm                          |7.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-11.1.106-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |COMMON_SET|Manifest: NOSIGNATURE
		simplyswords-forge-1.55.0-1.20.1.jar              |Simply Swords                 |simplyswords                  |1.55.0-1.20.1       |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.3.5-universal.jar                 |Forge                         |forge                         |47.3.5              |COMMON_SET|Manifest: ****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****
		appleskin-forge-mc1.20.1-2.5.0.jar                |AppleSkin                     |appleskin                     |2.5.0 mc1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
		PlayerRevive_FORGE_v2.0.26_mc1.20.1.jar           |PlayerRevive                  |playerrevive                  |2.0.26              |COMMON_SET|Manifest: NOSIGNATURE
		corpse-1.20.1-1.0.3.jar                           |Corpse                        |corpse                        |1.20.1-1.0.3        |COMMON_SET|Manifest: NOSIGNATURE
		DungeonsArise-1.20.1-2.1.56.1-beta.jar            |When Dungeons Arise           |dungeons_arise                |**.**.**.**-1.20.1     |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 4065783f-5515-4305-8ffa-cac67c372a3f
	FML: 47.3
	Forge: net.minecraftforge:47.3.5

### Logs

https://mclo.gs/CAW07JK

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

nope

**Comment by BlayTheNinth** [comment]
>  Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available

Your config file appears to be corrupt. Try deleting `balm-common.toml` from the config folder.

**Comment by BlottaOver** [comment]
> > Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
> 
> Your config file appears to be corrupt. Try deleting `balm-common.toml` from the config folder.

I looked in all the folders and couldn't find it
